name: Update Google Sheet
on:
  schedule:
    - cron: '0 * * * *' # Runs hourly
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install gspread oauth2client requests
      - name: Run script
        env:
        GCP_SERVICE_ACCOUNT_FILE: ${{ secrets.GCP_SERVICE_ACCOUNT_FILE }}
        run: python extractor.py
        
